** 目录
  108课大纲
** 一导引篇
   （该篇说明：课程72是缠中说禅为了方便后来者学习制定的一个懒人线路图学习方案）
*** 72：本ID已有课程的再梳理
	形态学，动力学的简单描述
	形态学是最根本的，形态学从本质上就是几何。
	动力学，是属于物理范畴的，本质上也是几何。
	动力学的前提条件 1、价格充分有效市场 2、非完全绝对趋同交易
	形态学包含 分型、笔、线段、中枢、走势类型等等
	动力学包含 背驰和涉及背驰的、中枢、走势能量等等
	学习路线：分型-笔-线段-最小级别中枢-各级别中枢-走势类型
** 二分型笔线段篇
   （该篇说明：中枢是分级别的，大级别总是由小级别慢慢生长出来的，
   那么最小级别中枢又是如何被最合理的构造出来呢，
   该篇就是中枢理论不得不学的基础课程部分之一）
*** 62：分型、笔与线段
	分型定义
	顶分型，第二K线高点是相邻三K线高点中最高的，而低点也是相邻三K线低点中最高的。
	底分型，第二K线低点是相邻三K线低点中最低的，而高点也是相邻三K线高点中最低的。
	顶和底，顶分型的最高点叫该分型的顶，底分型的最低点叫该分型的底。
	笔，两个相邻的顶和底之间构成一笔，最小的一笔要求顶和底之间至少有一个K线
	包含关系处理，向上时，把两K线的最高点当高点，而两K线低点中的较高者当成低点，合并成一K。
	上升的一笔，底分型+上升K线+顶分型
	下降的一笔，顶分型+下降K线+底分型
	（分型应该按最高价、最低价计算，还是应该用开盘价、收盘价计算？）
	建议顶分型，按最高价加蜡烛下沿，底分型，按最低价加蜡烛上沿，原因是包含关系就是这种处理办法
*** 65：再说说分型、笔、线段
	前后K线间的包含关系问题
	分析包含关系，要严格按照顺序，用第1、2分K线的包含关系确认新的K线，然后用新的K线去和第三根比。
	分型到笔，必须是一顶一底。
	两个顶或底中间没有其他的顶和底，需要忽略一个（忽略原则，取大优先，需验证！）
	所有的分型，都唯一地分解为上下交替的笔的连接。
	笔破坏，对于从向上一笔开始的其中的分型构成这样的序列：d1g1d2g2d2g3...dngn。
	如果找到i和j，j>=i+2，使得dj<=gi，那么称向上线段被笔破坏。
	线段分解定理，线段被破坏当且仅当至少被有重叠部分的连续三笔的其中一笔破坏。
	而只要构成有重叠部分的前三笔，那么必然会形成一线段，换言之，线段破坏的充要条件，就是被另一个线段破坏。

*** 67：线段的划分标准
	以向上笔开始的线段，可以用笔的序列表示：S1X1S2X2S3X3...SnXn，同理
	特征序列定义，序列X1X2...Xn成为以向上笔开始线段的特征序列
	序列S1S2...Sn成为以向下笔开始线段的特征序列
	特征序列缺口定义，特征序列的两相邻元素间没有重合区间，称为该序列的一个缺口
	标准特征序列定义，经过非包含处理的特征序列，成为标准特征序列
	以后没有特别说明，特征序列都是指标准特征序列
	特征序列的顶和底，
	以向上笔开始的线段的特征序列，只考察顶分型
	以向上笔开始的线段的特征序列，只考察底分型
	线段破坏的两种情况（以顶分型为例）：
	第一种情况，特征序列的顶分型中，第一和第二元素间不存在特征序列的缺口，
	那么该线段在该顶分型的高点处结束，该高点是该线段的终点
	第二种情况，特征序列的顶分型中，第一和第二元素间存在特征序列的缺口，
	如果从该顶分型最高点开始的向下一笔开始的序列的特征序列，出现底分型，
	那么该线段在该顶分型的高点处结束，该高点是该线段的终点
	想一想，如果没有出现会怎么样呢？

*** 69：月线分段与上海大走势分析、预判
	理论的核心，走势必完美。
*** 71：线段划分标准的再分辨（有一个图错误，在课程81有说明）
	越说越乱，抽空细看
*** 77：一些概念的再分辨（介绍到了缺口、分型、笔、线段的释义）
	缺口定义，在K线图上，两相邻的K线间出现没有成交的区间
	缺口回补，在缺口出现后，该缺口区间最终全部再次出现成交的过程
	走势行情力度分类：
	缺口不回补，强势（突破性缺口极少回补）
	缺口回补后继续新高或新低，平势（中继性缺口，回补几率对半）
	缺口回补后不能新高或新低，因而出现原来走势的转折，弱势
	（衰竭性缺口，一旦出现，就一定出现较大级别的调整。一个日线级别趋势的衰竭性缺口，至少制造一个周线级别的调整）
	盘整走势中的缺口，与在趋势中的缺口性质不同，盘整走势中的缺口属于普通缺口，一般都回补，而且没有太大的分析意义。
	（何为趋势？何为盘整？定义呢？）
	分型、笔的划分步骤：确定所有符合标准的分型，如果前后两个分型是同一性质的，（取大优先，相等时取前一个）
	线段中包含笔的数目，都是单数的。线段必须被线段所破坏才能确定其完成。
	
*** 78：继续说线段的划分 
	所有古怪的线段，都是因为线段出现第一种情况的笔破坏后，最终没有在该方向由该笔发展成线段破坏所造成的，这是线段古怪的唯一原因
	注意，线段最终肯定都会被线段破坏，但线段出现笔破坏后，最终并不一定在该方向由该笔发展，形成笔破坏
	很古怪，搞不太明白，回头再看
** 三中枢、走势类型和买买点篇
   （该篇说明：该篇既是中枢理论的基础课程，也是中枢理论的核心部分。从中枢定义到最小级别中枢，再到各级别中枢、各级别走势类型与买买点，该篇都有系统介绍）
*** 17：走势终完美
	任何级别的所有走势，都能分解成趋势与盘整两类，趋势又分为上涨与下跌两类（怎么画出明确的起点终点）
	缠中说禅技术分析基本原理一，任何级别的任何走势类型终要完成（走势终完美）
	走势终完美的含义：
	1、任何走势，无论是趋势还是盘整，在图形上最终都要完成
	2、一旦某种类型的走势完成以后，就会转化为其他类型的走势
	缠中说禅走势中枢定义：
	某级别走势类型中，被至少三个连续次级别走势类型所重叠的部分。
	最后不能分解的级别，定义为至少三个该级别单位K线重叠部分。
	缠中说禅盘整定义：
	在任何级别的任何走势中，某完成的走势类型只包含一个缠中说禅走势中枢，就称为该级别的缠中说禅盘整
	缠中说禅趋势定义：
	在任何级别的任何走势中，某完成的走势类型至少包含两个以上依次同向的缠中说禅走势中枢，就称为该级别的缠中说禅趋势
	缠中说禅技术分析基本原理二，任何级别任何完成的走势类型，必然包含一个以上的缠中说禅走势中枢
	缠中说禅走势分解定理一，任何级别的任何走势，都可以分解成同级别 盘整 下跌 与 上涨 三种走势类型的连接
	缠中说禅走势分解定理二，任何级别的任何走势类型，都至少由三段以上次级别走势类型构成
	缠中说禅买卖点定律一，任何级别的第二类买卖点都由次级别相应走势的第一类买卖点构成
	缠中说禅趋势转折定律（某级别）
	1、任何级别的上涨转折都是由某级别的第一类卖点构成的
	2、任何级别的下跌转折都是由某级别的第一类买点构成的
*** 83：笔-线段与线段-最小中枢结构的不同心理意义1
	线段构成最小中枢
*** 18：不被面首的雏男是不完美的（主要介绍中枢的生与死）
	如何判断一个走势类型完成了，这是技术分析里最核心的问题之一
	缠中说禅走势中枢的计算：具体的以前三个连续次级别类型的重叠为准（注意，前三个走势类型都是完成的才可以）
	走势类型延伸的实质：
	A、对于趋势来说：其延伸的实质就在于同级别的同向缠中说禅走势中枢不断产生
	B、对于盘整来说：其延伸的实质就在于不能产生新的缠中说禅走势中枢
	缠中说禅走势中枢定理一：在趋势中，连接两个同级别缠中说禅走势中枢的必然是次级别以下级别的走势类型。
	缠中说禅走势中枢定理二：在盘整中，无论是离开还是返回缠中说禅走势中枢的走势类型，必然是次级别以下的走势类型。
	缠中说禅走势中枢定理三：某级别缠中说禅走势中枢的破坏，当且仅当一个次级别走势离开该缠中说禅走势中枢后，其后的次级别走势类型回抽不重新回到该缠中说禅走势中枢内。

*** 63：替各位理理基本概念（主要对级别概念进行了形象的比喻和释义）
	操作步骤：
	1、确立显微镜倍数，例如我们把一分钟图作为最基本的图，那么就可以开始定义分型笔线段
	2、有了线段，就可以定义一分钟的中枢
	3、然后就是一分钟的走势类型（三段连续重叠的线段来定义一分钟中枢？）
	4、然后按照递归的方法，可以逐步定义五分钟、30分钟、日、周、月、季度、年的中枢和走势类型
*** 20：缠中说禅走势中枢级别扩张及第三类买卖点
	缠中说禅走势级别延续定理一：
	在更大级别缠中说禅走势中枢产生前，该级别走势类型将延续。也就是说，只能是只具有该级别缠中说禅走势中枢的盘整或趋势的延续。
	（本级别的线段被确认破坏前，当前线段将继续延伸）
	缠中说禅走势级别延续定理二：
	更大级别缠中说禅走势中枢产生，当且仅当围绕连续两个同级别缠中说禅走势中枢产生的波动区间，产生重叠。
	Z走势段：为方便起见，把这些与中枢方向一致的次级别走势类型成为Z（ABC中，A段和C段）。记号Zn，相应高低点gn、dn。
	定义四个指标：GG=max(gn)，G=min(gn)，D=max(dn)，DD=min(dn)
	再定义：ZG=min(g1,g2)，ZD=max(d1,d2)，显然，[ZD,ZG]就是缠中说禅走势中枢的区间。
	缠中说禅走势中枢中心定理一：走势中枢的延伸等价于任意区间[dn,gn]与[ZD,ZG]有重叠。
	换言之，若有Zn，使得dn>ZG或gn<ZD，则必然产生高级别的走势中枢，或趋势，及延续。
	缠中说禅走势中枢中心定理二：
	1、前后同级别的两个缠中说禅走势中枢，后GG<前DD等价于下跌及其延续。
	2、前后同级别的两个缠中说禅走势中枢，后DD>前GG等价于上涨及其延续。
	3、前后同级别的两个缠中说禅走势中枢，后ZG<前ZD且后GG>=前DD，则等价于形成高级别的走势中枢。
	4、前后同级别的两个缠中说禅走势中枢，后ZD>前ZG且后DD<=前GG，则等价于形成高级别的走势中枢。
	（如果两个中枢有交集，算什么？）
	第三类买卖点定理：
	一个次级别走势类型向上离开缠中说禅走势中枢，然后以一个次级别走势类型回试，其低点不跌破ZG，则构成第三类买点。
	一个次级别走势类型向下离开缠中说禅走势中枢，然后以一个次级别走势类型回抽，其高点不生破ZD，则构成第三类卖点。

*** 21：缠中说禅买卖点分析的完备性
	缠中说禅买卖点的完备性定理：
	市场必然产生盈利的买卖点，只有一、二、三类
	缠中说禅升跌完备性定理：
	市场中的任何向上与下跌，都必然从三类缠中说禅买卖点中的某一类开始以及结束
	换言之，市场走势完全由这样的线段构成，线段的端点是某级别的三类缠中说禅买卖点中的某一类
*** 35：给基础差的同学补补课
	（该课是在线段概念出现前的课程，如果已经认可3线段重叠构成最低级别的中枢1F中枢的统一定义，这课可以不看，否则容易对级别概念混乱）
	缠中说禅买卖点级别定理：
	大级别的买卖点必然是次级别以下某一级别的买卖点。
	注意，任何一次失误都要马上总结，不能连续失误再调整。
	注意，失误的原因永远与市场无关，找原因，只能找自己的原因
	问题无非几种，参与过小级别的操作、没有按买卖点操作、参与过于频繁、对图形判断不熟练、有盲点、乱听消息
*** 101：答疑1（介绍第二类买卖点和走势必完美的问题，可以加深相关概念理解）
	第一类买卖点就是背驰点，第三类买卖点就是中枢破坏点。
	第二类买点，就是第一类买点的次级别回抽结束后，再次探底或回试的那个次级别走势的结束点。
	站在原来下跌最后一个中枢的角度，第一、二、三类买点都可以看成是中枢震荡的结果
	走势必完美：
	分型、笔、线段、不同级别走势类型所对应的递归函数，能将行情的任何走势唯一地分解。
	
*** 102：再说走势必完美（包含级别和完全分类的释义）
	理论中，递归函数是有级别的，是级别依次升大的
	区间套的方法，是走势必完美的一个重要的应用，有了区间套，买卖点的精确定位才有可能。
	级别的存在，一个必然的结论就是，任何高级别的改变都必须先从低级别开始。
	
*** 53：三个买卖点的再分辨
	例如
	在看30分钟的第三类买卖点时，由于要涉及次级别5分钟的判断问题，所以那时候就不能光用30分钟级别的显微镜，同样要转换成5分钟的。
	背驰与盘整背驰：
	1、背驰是有着最基础意义的
	2、而盘整背驰，只是利用前者相应的力度分析方法进行的一个推广用法，主要用在与中枢震荡相关的力度比较中。
	第一、二、三买卖点，归根到底都可以归到第一类买卖点上，只是级别不同。
	因为不同级别的买卖点意义是不同的，因此要统一在一个级别上研究，这才有三个买卖点的区别。
	站在同一级别上，三个买卖点都重要：
	第一个买卖点，就是该级别的背驰点，这足以应付最大多数的情况。
	特殊情况就是，小级别转大级别的情况，原因：
	a、一般说，从高点一个次级别走势向下后接着一个次级别走势向上，如果不创新高或盘整背驰，都构成第二类卖点，而买点的情况反过来就是。
	所以，在有第一类买卖点的情况下，第一类买卖点是最佳的，第二类买卖点只是一个补充。
	b、但在小级别转大级别的情况下，第二类买卖点就是最佳的，因为在这种情况下，没有该级别的第一类买卖点。
	第二类买卖点，站在中枢形成的角度，其意义就是必然要形成更大级别的中枢
	第三类买卖点，其意义就是对付中枢结束的。
	
*** 56：530印花税当日行情图解（突发事件下的走势和操作实例）
	股票都是废纸，必须选好级别，在该级别的买点买、卖点卖，把成本降为0，只有成本为0的股票才是真正安全的。
	第二类卖点除了在小级别转大级别上比第一类卖点优越，在一些特殊的突发情况下，就是最佳的卖点。
	实践课，回头再看
** 四背驰篇
   （该篇说明：所谓的当下判断和操作往往离不开对某级别走势背驰的判断，该篇是中枢课程动力学部分最基础的内容了）
*** 24：MACD对背驰的辅助判断
	出现背驰后必然有逆转，这是没有任何商量余地的。
	背驰后究竟逆转多少？很简单，就是重新出现新的次级别买卖点为止。
	缠中说禅背驰-买卖点定理：
	任一背驰都必然制造某级别的买卖点，任一级别的买卖点都必然源自某级别走势的背驰。
	换句话说，只要你看到某级别的背驰，必然要意味着要有逆转，但逆转并不意味着永远的逆转。
	用MACD判断背驰的前提是：
	A、B、C段在一个大的趋势里，其中A之前已经有一个中枢，而B是这个大趋势的另一个中枢，B这个中枢一般会把MACD的黄白线
	（也就是DIFF和DEA）回拉到0轴附近。而C段的走势类型完成时，对应的MACD柱子面积（向上的看红柱子，向下的看绿柱子）比A段对应的面积要小，这时候就构成标准的背驰。
	盘整中的类似背驰方法的应用，称为盘整背驰判断。
	以盘整中往上的情况为例：
	A、不破中枢的盘整背驰情况：
	如果C段不破中枢，一旦出现MACD柱子的C段面积小于A段面积，其后必定有回跌。
	B、破中枢的盘整背驰情况：
	比较复杂的是如果C段上破中枢，但MACD柱子的面积小于A段的，这时候的原则是先出来，其后有两种情况：
	a、如果回跌不重新跌回，就在次级别的第一类买点回补，刚好这反而构成该级别的第三类买点；
	b、反之就继续盘整。
	要精确地判断背驰与盘整背驰，还是要从中枢本身出发。
*** 25：吻，MACD、背驰、中枢
	一定要先分清楚趋势和盘整，然后再搞清楚背驰与盘整背驰。
	一个标准的两个中枢的上涨，在MACD上会表现出这样的形态：
	1、就是第一段，MACD的黄白线从0轴下面上穿上来，在0轴上方停留的同时，形成相应的第一个中枢，
	同时形成第二类买点，其后突破该中枢，MACD的黄白线也快速拉起，这往往是最有力度的一段，一切的趋势延伸等等，
	以及MACD绕来绕去的所谓指标钝化都经常出现在这一段，这段一般在一个次级别的背驰中结束，
	然后进入第二个中枢的形成过程中；
	2、在第二个中枢的形成过程中，同时MACD的黄白线会逐步回到0轴附近。
	3、最后，开始继续突破第二个中枢，MACD的黄白线以及柱子都再次重复前面的过程，但这次，黄白线不能创新高，
	或者柱子的面积或者伸长的高度能不能突破新高，出现背驰，这就结束了这一个有两个中枢的上涨过程。
	示例000572
	注意！各位一定要把MACD判断背驰的几个条件综合起来。

*** 27：盘整背驰与历史性底部
	趋势，一定有至少两个同级别中枢，对于背驰来说，肯定不会发生在第一个中枢之后，肯定是至少是第二个中枢之后。
	第二个中枢后就产生背驰的情况，一般占了绝大多数的情况。
	如果在第一个中枢就出现背驰，那不会是真正意义上的背驰，只能算是盘整背驰。
	盘整背驰真正的技术含义，其实就是一个企图脱离中枢的运动，由于力度有限，被阻止而出现回到中枢里。
	多数的第二、三类买点，其实都是由盘整背驰构成的，而第一类买点，多数由趋势的背驰构成
	第二、三类的买点，都有一个三段的走势，第三段往往都破一点第一段的极限位置，从而形成盘整背驰，
	注意这里把第一、第三段看成两个走势类型之间的比较，和趋势背驰里的情况有所不同，
	两个盘整在盘整背驰中也是可以比较力度的。
	背驰段定义：
	就是在某级别的某类型走势，如果构成背驰或盘整背驰，就把这段走势类型称为某级别的背驰段
	盘整背驰最有用的是用在大级别上，至少周线级别以上的，配合MACD，这种背驰是很容易判断的。

*** 29：转折的力度与级别
*** 37：背驰的再分辨
	感觉没什么东西
*** 43：有关背驰的补习课
	感觉没什么东西
*** 44：小级别背驰引发大级别转折

*** 64：去机场路上给各位补课（macd对背驰辅助判断的一个实例)
*** 61：区间套定位标准图解（分析示范六）
** 五同级别分解篇
   （该篇说明：合理的走势分解对把握当下走势非常关键，最简单的走势分解就是进行同级别分解，所以该篇也应该算是必须掌握的中枢基础课程部分）
*** 33：走势的多样性
*** 36：走势类型连接结合性的简单运用
*** 38：走势类型连接的同级别分解
*** 39：同级别分解再研究
*** 40：同级别分解的多重赋格
** 六实战操作策略篇
   （该篇说明：中枢理论如何具体应用到股票的买卖操作上，该篇就是解决这个问题的，所以当然也是中枢理论基础课程）
*** 26：市场风险如何回避
*** 31：资金管理的最稳固基础
*** 32：走势的当下与投资者的思维方式
*** 41：没有节奏，只有死
*** 45：持股与持币，两种最基本的操作
*** 46：每日走势的分类
*** 47：一夜情行情分析
*** 48：暴跌，牛市行情的一夜情
*** 49：利润最大的操作模式
*** 50：操作中的一些细节问题
*** 55：买之前戏，卖之高潮
*** 68：走势预测的精确意义
*** 73：市场获利机会的绝对分类
*** 74：如何躲避政策性风险
*** 92：中枢震荡的监视器
*** 106：均线、轮动与缠中说禅板块强弱指标
*** 107：如何操作短线反弹
*** 108：何谓底部？从月线看中期走势演化
** 七走势与买买点的动态和立体分析篇
   （该篇说明：该篇是属于现有中枢理论课程的高级内容，如果说基础课程可以解决绝大部分的市场问题的话，那该篇就属于实战中不断精进操作水平需要掌握的理论武器）
*** 86：走势分析中必须杜绝一根筋思维
*** 70：一个教科书式走势的示范分析（介绍包括当下走势组合的实例分析）
*** 79：分型的辅助操作与一些问题的再解答
*** 82：分型结构的心理因素
*** 88：图形生长的一个具体案例（引入走势的中阴阶段概念）
*** 89：中阴阶段的具体分析
*** 90：中阴阶段结束时间的辅助判断
*** 91：走势结构的两重表里关系1
*** 93：走势结构的两重表里关系2
*** 99：走势结构的两重表里关系3
** 八心态篇
   （该篇说明：顾名思义，该篇是要解决技术解决不了的问题，也就是操作的另外一面，人的问题）
*** 80：市场没有同情、不信眼泪
*** 19：学习缠中说禅技术分析理论的关键
*** 23：市场与人生
*** 34：宁当面首 莫成怨男
*** 42：有些人是不适合参与市场的
*** 94：当机立断
*** 95：修炼自己
*** 96：无处不在的赌徒心理
*** 105：远离聪明、机械操作
** 九兵法篇
  （该篇说明：当你已经成为市场的大佬，该篇才是你需要关注的）
*** 28：下一目标 摧毁基金
*** 51：短线股评荐股者的传销把戏
*** 66：主力资金的食物链
*** 97：中医、兵法、诗歌、操作1
*** 98：中医、兵法、诗歌、操作2
*** 100：中医、兵法、诗歌、操作3
** 十中枢理论自身体
   （该篇说明：当你对中枢理论本身还有这样那样的疑问担心质疑的时候，看看以下的课程内容吧，实在还解决不了你的担心疑问，那就远离中枢理论吧，别跟自己较劲。）
*** 30：缠中说禅理论的绝对性
*** 52：炒股票就是真正的学佛（有一处笔误）
*** 81：图例、更正及分型、走势类型的哲学本质
*** 84：本理论一些必须注意的问题
** 十一中枢理论未竟篇
   （该篇说明：缠君还有很多中枢理论课程和文化方面的内容需要向有缘的朋友介绍，相信这不会是最终的未竟篇）
*** 104：几何结构与能量动力结构1
** 十二缠君与市场篇
   （该篇说明：炒股课程，“全中国不会有第二人比本ID更适合写的”，没有在资本市场的翻江倒海，怎么可能产生如此的气魄。以下市场痕迹相信不过是缠君在资本市场倒腾的冰山一角。）
*** 22：将8亿的大米装到5个庄家的肚里
*** 75：逗庄家玩的一些杂史1
*** 76：逗庄家玩的一些杂史2
*** 85：逗庄家玩的一些杂史3
*** 87：逗庄家玩的一些杂史4
** 十三中枢理论前传篇
   （该篇说明：该篇除了与心态篇相类似的一些内容，其实本身并不属于中枢理论课程部分，这在课程72也就是导引篇已经有介绍了，因此大家可以作为一种前传篇来阅读，如果你的脑子不容易分清该篇与中枢理论的关系，还是不学也罢，省得捡了芝麻丢了西瓜，把理论与非理论混淆不清了）
*** 1～15
*** 16：中小资金的高效买卖法
*** 103：学屠龙术前先学好防狼术
** 十四线段概念出现之前的走势实例讲解篇
   （该篇说明：该篇虽说也属于中枢理论课程范畴，但是都是在分型、笔、线段篇课程出现之前介绍的，如果你对中枢和级别还达不到相当的理解和应用水准，该篇不看也罢，免得引起质疑中枢标准前后不一致这样的无聊问题。）
*** 54：一个具体走势的分析
*** 57：当下图解分析再示范
*** 58：图解分析示范三
*** 59：图解分析示范四
*** 60：图解分析示范五
*** 61：区间套定位标准图解（分析示范六）
